/**
 * `cf-push` — push the active festival's lineup to a Clashfinder event. Extracted
 * from the CLI dispatch: it two-phase pushes (schedule live now with whatever mbids
 * + blurbs are cached, then resolves the rest from MusicBrainz / the festival bios
 * and re-pushes enriched), reusing the shared MBID cache and a name->blurb cache.
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { loadCfOverrides, applyDisplayNames } from "./cf-overrides.js";
import {
  foreignEdit,
  fetchRevisions,
  lastEditorIsUs,
  compareUrl,
  type Revision,
  diffMirror,
  plausibleEdit,
  loadPushState,
  savePushState,
  mirrorActsFromEvent,
  cfLocalStamp,
  readClashfinderEvent,
} from "./cf-guard.js";
import {
  toClashfinderFields,
  pushClashfinder,
  clashfinderUserLogin,
  createMbidResolver,
  htmlToBlurb,
  parseGets,
  buildEventMap,
  httpGet,
  httpGetJson,
} from "@festival-bot/adapters";
import { loadSecrets, cacheDir, REPO_ROOT } from "./config.js";
import { starStateFrom, diffStars, renderStarDiff, type StarState, type UserStarDiff } from "./star-watch.js";
import { ACTIVE_FESTIVAL } from "./festivals.js";
import type { Runtime } from "./runtime.js";

function takeFlag(args: string[], flag: string): { value?: string; rest: string[] } {
  const i = args.indexOf(flag);
  if (i < 0) return { rest: args };
  return { value: args[i + 1], rest: [...args.slice(0, i), ...args.slice(i + 2)] };
}

/** Stage display order on the mirror = the venue list order (each festival orders
 *  its venues.json to match its canonical order, e.g. the ATN app's stage order). */
export function stageOrderFn(rt: Runtime): (slug: string) => number {
  const venueRank = new Map(rt.module.venues.venues.map((v, i) => [v.slug, i]));
  return (slug: string) => venueRank.get(slug) ?? Number.MAX_SAFE_INTEGER;
}

export async function runCfPush(rt: Runtime, tz: string, args: string[]): Promise<void> {
  const log = (s: string): void => console.log(s);
  const noMbid = args.includes("--no-mbid");
  // Set once the operator has looked at a foreign edit and said go.
  const accepted = args.includes("--accept-remote");
  const noteFlag = takeFlag(
    args.filter((a) => a !== "--no-mbid" && a !== "--accept-remote"),
    "--note",
  );
  const pushArgs = noteFlag.rest;
  const event = pushArgs[0];
  if (!event) return void log('usage: cf-push <cf-event-slug> [--note "..."] [--no-mbid]');
  const cf = loadSecrets().clashfinder;
  // Prefer deriving the login from the password (always fresh); fall back to a
  // stored userLogin token.
  const userLogin = cf?.password ? clashfinderUserLogin(cf.authUsername, cf.password) : cf?.write?.userLogin;
  if (!userLogin) {
    return void log("no clashfinder password or write.userLogin in config/secrets.json — can't push.");
  }
  const m = rt.module.manifest;
  const baseNote = noteFlag.value ?? `festival-bot ${new Date().toISOString().slice(0, 10)}`;
  const today = new Date().toISOString().slice(0, 10);
  // rt.sets already includes any extra-sets.json entries (merged in runtime.ts),
  // so the mirror and the planner push the same festival.
  //
  // Display overrides are applied HERE and nowhere else: the mirror gets the
  // human-readable label, the planner keeps the feed's name so favourites keep
  // resolving. This is what stops our push wiping a Clashfinder user's hand
  // edits every sync (operator note, 2026-08-01).
  const overrides = loadCfOverrides(join(REPO_ROOT, "festivals", ACTIVE_FESTIVAL, "cf-overrides.json"));
  const sets = applyDisplayNames(rt.sets, overrides);
  const names = [...new Set(sets.map((s) => s.name))];

  const stageOrder = stageOrderFn(rt);

  const buildFields = (mbids: Map<string, string>, blurbs: Map<string, string>) =>
    toClashfinderFields(sets, {
      timezone: tz,
      mainTitle: m.name,
      stageName: (s) => rt.venueName(s),
      dayChangeoverHour: m.dayCutoffHour,
      footer: ["Times liable to change", `Generated by festival-bot ${today}`],
      stageOrder,
      // artist (suffix-stripped name) is auto-derived by the exporter.
      extras: (s) => ({ mbid: mbids.get(s.name), blurb: blurbs.get(s.name) }),
    });
  // ---- Guard: has anyone else edited the mirror since we last pushed? ----
  // Operator note, 2026-08-01, after our push destroyed a user's Seanchoíche entries:
  // check the last editor, pull the diff, and DO NOT push until the operator has made a
  // go/no-go call. Our push replaces the whole event, so this is the only thing
  // standing between a contributor's work and an automated delete.
  const stateFile = join(cacheDir(ACTIVE_FESTIVAL), `cf_push_state_${event}.json`);
  const ourActs = sets.map((s) => ({
    name: s.name,
    stage: rt.venueName(s.stage),
    start: cfLocalStamp(s.start, tz),
  }));
  if (!accepted && cf?.authUsername && cf.authPublicKey) {
    const ev = await readClashfinderEvent(event, cf.authUsername, cf.authPublicKey).catch(() => null);
    // The revision log names the author outright, so prefer it; fall back to
    // comparing the lastEdit we recorded after our own push.
    const revs = await fetchRevisions(event).catch(() => [] as Revision[]);
    const someoneElse = revs.length
      ? !lastEditorIsUs(revs, cf.authUsername)
      : foreignEdit(ev?.lastEdit ?? "", loadPushState(stateFile), event);
    if (ev) {
      if (someoneElse) {
        const diff = diffMirror(mirrorActsFromEvent(ev), ourActs);
        const who = revs[0] ? `${revs[0].by} (rev ${revs[0].rev}: ${revs[0].note || "no note"})` : `lastEdit ${ev.lastEdit}`;
        const mine = revs.find((r) => r.by.toLowerCase() === cf.authUsername.toLowerCase());
        if (plausibleEdit(diff)) {
          log(`HOLDING PUSH — last edit was by ${who}, not us.`);
          if (mine && revs[0]) log(`  compare: ${compareUrl(event, mine.rev, revs[0].rev)}`);
          log(`  ${diff.theirsOnly.length} act(s) on the mirror that our push would DELETE:`);
          for (const a of diff.theirsOnly.slice(0, 20)) log(`    - ${a.name} @ ${a.stage} (${a.start})`);
          for (const r of diff.retimed.slice(0, 10)) log(`    ~ ${r.name}: mirror ${r.theirs} vs ours ${r.ours}`);
          if (diff.oursOnly.length) log(`  ${diff.oursOnly.length} of ours the mirror lacks (would be added).`);
          log("  Nothing pushed. Decide, then re-run with --accept-remote to overwrite,");
          log("  or fold their entries into extra-sets.json / cf-overrides.json first.");
          return;
        }
        if (diff.theirsOnly.length + diff.retimed.length > 0) {
          log(`HOLDING PUSH — the mirror differs from us by ${diff.theirsOnly.length + diff.retimed.length} acts.`);
          log("  Too large to be a hand edit; something is wrong with one side. Nothing pushed.");
          return;
        }
      }
    }
  }

  const doPush = async (mbids: Map<string, string>, blurbs: Map<string, string>, revNote: string): Promise<void> => {
    const res = await pushClashfinder(
      event,
      { ...buildFields(mbids, blurbs), desc: m.name, revNote },
      { userLogin, phpsessid: cf?.write?.phpsessid },
    );
    if (res.ok) {
      log(`  pushed ${sets.length} acts (${mbids.size} mbids, ${blurbs.size} blurbs) -> clashfinder.com/s/${event} [${revNote}]`);
      // Record the mirror's lastEdit as it stands AFTER our write, so the next
      // run can tell our own edit from somebody else's.
      if (cf?.authUsername && cf.authPublicKey) {
        const after = await readClashfinderEvent(event, cf.authUsername, cf.authPublicKey).catch(() => null);
        if (after?.lastEdit) {
          savePushState(stateFile, {
            event,
            lastEdit: after.lastEdit,
            pushedAt: new Date().toISOString(),
            actCount: sets.length,
          });
        }
      }
    }
    else if (res.staleSession)
      log(`  STALE SESSION (login wall, ${res.finalUrl}) — refresh clashfinder.password / write.userLogin in secrets.`);
    else log(`  push not confirmed: HTTP ${res.status}, final URL ${res.finalUrl}`);
  };

  // mbid enrichment (MusicBrainz, cached/throttled); skipped with --no-mbid.
  const resolver = createMbidResolver({ cacheFile: join(cacheDir("musicbrainz"), "mbid.json") });
  const mbidSplit = noMbid
    ? { found: new Map<string, string>(), missing: [] as string[] }
    : resolver.cachedOnly(names);

  // blurb enrichment (festival bios via artistInfo -> htmlToBlurb), name->blurb cache.
  const info = rt.module.sources.artistInfo;
  const slugOf = new Map(rt.sets.map((s) => [s.name, s.slug]));
  const blurbFile = join(cacheDir(ACTIVE_FESTIVAL), "blurbs.json");
  const blurbCache: Record<string, string> = (() => {
    try {
      return JSON.parse(readFileSync(blurbFile, "utf8")) as Record<string, string>;
    } catch {
      return {};
    }
  })();
  const cachedBlurbs = new Map<string, string>();
  const missingBlurbs: string[] = [];
  for (const n of names) {
    if (n in blurbCache) {
      if (blurbCache[n]) cachedBlurbs.set(n, blurbCache[n]!);
    } else if (info) {
      missingBlurbs.push(n);
    }
  }
  const resolveBlurbs = async (): Promise<Map<string, string>> => {
    const out = new Map(cachedBlurbs);
    if (!info || missingBlurbs.length === 0) return out;
    for (const n of missingBlurbs) {
      const blurb = htmlToBlurb((await info.info(slugOf.get(n)!)).bio);
      blurbCache[n] = blurb; // cache hits and misses
      if (blurb) out.set(n, blurb);
    }
    mkdirSync(dirname(blurbFile), { recursive: true });
    writeFileSync(blurbFile, JSON.stringify(blurbCache, null, 2));
    return out;
  };

  // Runs on EVERY exit path. The fully-cached branch below returns early, and the
  // first cut of this hung the check off the end of the function only — so on a
  // push where nothing needed enrichment (the common case once MBIDs and blurbs
  // are warm) it silently never ran.
  const starCheck = async (): Promise<void> => {
    if (cf?.authUsername && cf.authPublicKey) {
      await reportStarDamage(event, cf.authUsername, cf.authPublicKey, log);
    }
  };

  const needsResolution = mbidSplit.missing.length > 0 || missingBlurbs.length > 0;
  if (!needsResolution) {
    await doPush(mbidSplit.found, cachedBlurbs, baseNote);
    await starCheck();
    return;
  }

  // Two-phase: push the schedule live now with whatever's cached, then resolve
  // the rest (mbids from MusicBrainz, blurbs from the festival bios) and re-push.
  log(
    `phase 1: pushing schedule now (mbids ${mbidSplit.found.size}/${names.length}${noMbid ? " [skipped]" : ""}, ` +
      `blurbs ${cachedBlurbs.size}/${names.length} cached; ${mbidSplit.missing.length} mbids + ${missingBlurbs.length} blurbs to resolve)…`,
  );
  await doPush(mbidSplit.found, cachedBlurbs, `${baseNote} (schedule)`);
  log("phase 2: resolving enrichment (MusicBrainz throttled ~1/s; cached after)…");
  const fullMbids = noMbid ? mbidSplit.found : await resolver.resolveAll(names);
  const fullBlurbs = await resolveBlurbs();
  log(`phase 2: re-pushing enriched (${fullMbids.size} mbids, ${fullBlurbs.size} blurbs)…`);
  await doPush(fullMbids, fullBlurbs, `${baseNote} (enriched)`);

  // Operator note, 2026-07-28: keep pushing, but say so when a push breaks someone's star.
  await starCheck();
}

/**
 * After a push, re-resolve every crew member's highlight codes against the new
 * event map and report any that stopped resolving or now point at a different
 * act. Best-effort: a failure here must never fail the push itself, since the
 * mirror is already live by this point.
 */
async function reportStarDamage(
  event: string,
  authUsername: string,
  authPublicKey: string,
  log: (s: string) => void,
): Promise<void> {
  const stateFile = join(cacheDir(ACTIVE_FESTIVAL), "star_state.json");
  try {
    const users = (
      JSON.parse(readFileSync(join(REPO_ROOT, "data", "users.json"), "utf8")) as {
        users: Record<string, { clashfinder?: string }>;
      }
    ).users;
    const authQ = new URLSearchParams({ authUsername, authPublicKey });
    const ev = await httpGetJson<Parameters<typeof buildEventMap>[0]>(
      `https://clashfinder.com/data/event/${event}.json?${authQ}`,
    );
    const codeToName = buildEventMap(ev);

    let prev: Record<string, StarState> = {};
    try {
      prev = JSON.parse(readFileSync(stateFile, "utf8")) as Record<string, StarState>;
    } catch {
      // first run: nothing to compare against, just record the baseline
    }

    const next: Record<string, StarState> = {};
    const diffs: UserStarDiff[] = [];
    for (const [handle, u] of Object.entries(users)) {
      if (!u.clashfinder) continue;
      const html = await httpGet(
        `https://clashfinder.com/m/${event}/?user=${encodeURIComponent(u.clashfinder)}`,
      );
      next[handle] = starStateFrom(parseGets(html), codeToName);
      if (prev[handle]) diffs.push({ handle, diff: diffStars(prev[handle]!, next[handle]!) });
    }

    const report = renderStarDiff(diffs);
    if (report) log(report);
    mkdirSync(dirname(stateFile), { recursive: true });
    writeFileSync(stateFile, JSON.stringify(next, null, 2));
  } catch (e) {
    log(`  (star check skipped: ${(e as Error).message})`);
  }
}
