import { createHash } from "node:crypto";
import { describe, expect, test } from "vitest";
import type { ArtistSet } from "@festival-bot/core";
import {
  toClashfinderAct,
  toClashfinderSetup,
  toClashfinderFields,
  buildClashfinderPushBody,
  pushClashfinder,
  clashfinderUserLogin,
  htmlToBlurb,
} from "./clashfinder-export.js";

const mbv: ArtistSet = {
  name: "My Bloody Valentine",
  slug: "mbv",
  stage: "revolut",
  start: new Date("2026-06-06T20:05:00Z"), // 22:05 CEST
  end: new Date("2026-06-06T21:05:00Z"), // 23:05 CEST
  durationMin: 60,
};

const stageName = (slug: string): string => (slug === "revolut" ? "Revolut" : slug);

describe("toClashfinderAct", () => {
  test("emits a JSON act line with local wall time and display stage", () => {
    const line = toClashfinderAct(mbv, { timezone: "Europe/Madrid", stageName });
    expect(line).toBe(
      'act = {"start":"2026-06-06 22:05","end":"2026-06-06 23:05","stage":"Revolut","act":"My Bloody Valentine"}',
    );
  });

  test("keeps commas in act names safe (inside the JSON string)", () => {
    const csn: ArtistSet = { ...mbv, name: "Crosby, Stills and Nash", slug: "csn" };
    const line = toClashfinderAct(csn, { timezone: "Europe/Madrid" });
    expect(line).toContain('"act":"Crosby, Stills and Nash"');
    expect(JSON.parse(line.slice("act = ".length)).act).toBe("Crosby, Stills and Nash");
  });

  test("includes optional blurb/url and the estd flag when set", () => {
    const line = toClashfinderAct(mbv, {
      timezone: "Europe/Madrid",
      stageName,
      blurb: "shoegaze legends",
      url: "https://mbv.example",
      estimated: true,
    });
    const obj = JSON.parse(line.slice("act = ".length));
    expect(obj.blurb).toBe("shoegaze legends");
    expect(obj.url).toBe("https://mbv.example");
    expect(obj.estd).toBe("1");
  });

  test("includes mbid when provided", () => {
    const line = toClashfinderAct(mbv, { timezone: "Europe/Madrid", stageName, mbid: "abc-123-def" });
    expect(JSON.parse(line.slice("act = ".length)).mbid).toBe("abc-123-def");
  });

  test("auto-sets artist to the suffix-stripped name when it differs", () => {
    const dj: ArtistSet = { ...mbv, name: "Fatboy Slim (DJ Set)", slug: "fbs" };
    const obj = JSON.parse(toClashfinderAct(dj, { timezone: "Europe/Madrid" }).slice("act = ".length));
    expect(obj.act).toBe("Fatboy Slim (DJ Set)");
    expect(obj.artist).toBe("Fatboy Slim");
  });

  test("omits artist when it equals the act name", () => {
    const obj = JSON.parse(toClashfinderAct(mbv, { timezone: "Europe/Madrid" }).slice("act = ".length));
    expect(obj.artist).toBeUndefined();
  });

  test("includes a blurb with \\n\\n paragraph breaks when provided", () => {
    const obj = JSON.parse(
      toClashfinderAct(mbv, { timezone: "Europe/Madrid", blurb: "First.\n\nSecond." }).slice("act = ".length),
    );
    expect(obj.blurb).toBe("First.\n\nSecond.");
  });

  test("defaults stage to the slug when no name mapper is given", () => {
    const line = toClashfinderAct(mbv, { timezone: "Europe/Madrid" });
    expect(JSON.parse(line.slice("act = ".length)).stage).toBe("revolut");
  });
});

describe("htmlToBlurb", () => {
  test("strips tags and joins paragraphs with blank lines", () => {
    expect(htmlToBlurb("<p>First para.</p><p>Second para.</p>")).toBe("First para.\n\nSecond para.");
  });
  test("treats <br> as a paragraph break and decodes entities", () => {
    expect(htmlToBlurb("Rock &amp; roll<br>Next line")).toBe("Rock & roll\n\nNext line");
  });
  test("collapses inner whitespace and trims", () => {
    expect(htmlToBlurb("  <p>  hello   world  </p>  ")).toBe("hello world");
  });
  test("returns empty for empty/tag-only html", () => {
    expect(htmlToBlurb("")).toBe("");
    expect(htmlToBlurb("<p></p>")).toBe("");
  });
});

describe("toClashfinderSetup", () => {
  const second: ArtistSet = {
    name: "Charli XCX",
    slug: "charli-xcx",
    stage: "estrella-damm",
    start: new Date("2026-06-06T19:00:00Z"),
    end: new Date("2026-06-06T20:00:00Z"),
    durationMin: 60,
  };

  test("emits a header then one act line per set, sorted by start time", () => {
    const out = toClashfinderSetup([mbv, second], {
      timezone: "Europe/Madrid",
      mainTitle: "Primavera Sound 2026",
      stageName,
      footer: ["Generated by psbot"],
      hashtags: ["#PS2026"],
    });
    const lines = out.trimEnd().split("\n");
    expect(lines[0]).toBe("mainTitle = Primavera Sound 2026");
    expect(out).toContain("hashtags = #PS2026");
    expect(out).toContain("footer = Generated by psbot");
    const actLines = lines.filter((l) => l.startsWith("act = "));
    expect(actLines).toHaveLength(2);
    // sorted by start: Charli (19:00Z) before MBV (20:05Z)
    expect(actLines[0]).toContain('"act":"Charli XCX"');
    expect(actLines[1]).toContain('"act":"My Bloody Valentine"');
  });
});

describe("toClashfinderFields (editor input0/input1 split)", () => {
  test("puts directives in input0 and act lines in input1", () => {
    const f = toClashfinderFields([mbv], {
      timezone: "Europe/Madrid",
      mainTitle: "PS26",
      stageName,
      dayChangeoverHour: 8,
      footer: ["Times liable to change"],
    });
    expect(f.input0).toContain("maintitle = PS26");
    expect(f.input0).toContain("timezone = Europe/Madrid");
    expect(f.input0).toContain("daychangeover = 08:00");
    expect(f.input0).toContain("footer = Times liable to change");
    expect(f.input0).toContain("lpRevisions");
    expect(f.input0).not.toContain("act = ");
    expect(f.input1).toContain('act = {"start":"2026-06-06 22:05"');
    expect(f.input1).not.toContain("maintitle");
  });

  test("stageOrder groups stages by rank so the mirror matches it (overriding time order)", () => {
    const charli: ArtistSet = {
      name: "Charli XCX",
      slug: "charli-xcx",
      stage: "estrella-damm",
      start: new Date("2026-06-06T19:00:00Z"), // earlier than mbv (revolut, 20:05Z)
      end: new Date("2026-06-06T20:00:00Z"),
      durationMin: 60,
    };
    // Rank revolut before estrella-damm, i.e. against chronological order.
    const rank: Record<string, number> = { revolut: 0, "estrella-damm": 1 };
    const f = toClashfinderFields([charli, mbv], {
      timezone: "Europe/Madrid",
      stageName,
      stageOrder: (s) => rank[s] ?? 99,
    });
    const acts = f.input1.split("\r\n").filter((l) => l.startsWith("act = "));
    // revolut (rank 0) first despite its later start time -> mirror shows Revolut first.
    expect(acts[0]).toContain('"act":"My Bloody Valentine"');
    expect(acts[1]).toContain('"act":"Charli XCX"');
  });

  test("without stageOrder, acts stay in chronological order", () => {
    const charli: ArtistSet = {
      name: "Charli XCX",
      slug: "estrella-damm",
      start: new Date("2026-06-06T19:00:00Z"),
      end: new Date("2026-06-06T20:00:00Z"),
      durationMin: 60,
    } as ArtistSet;
    const f = toClashfinderFields([mbv, charli], { timezone: "Europe/Madrid", stageName });
    const acts = f.input1.split("\r\n").filter((l) => l.startsWith("act = "));
    expect(acts[0]).toContain('"act":"Charli XCX"'); // 19:00Z before mbv 20:05Z
  });
});

describe("clashfinderUserLogin", () => {
  test("derives the login cookie token as user + ',' + sha1(user+password)", () => {
    const tok = clashfinderUserLogin("demo", "pw123");
    const expected = "demo," + createHash("sha1").update("demopw123").digest("hex");
    expect(tok).toBe(expected);
    expect(tok.split(",")[1]).toHaveLength(40);
  });
});

describe("buildClashfinderPushBody", () => {
  test("encodes the editor form fields", () => {
    const body = buildClashfinderPushBody({
      input0: "maintitle = X",
      input1: "act = {}",
      desc: "My Event",
      revNote: "psbot 2026-06-18",
    });
    const p = new URLSearchParams(body);
    expect(p.get("input0")).toBe("maintitle = X");
    expect(p.get("input1")).toBe("act = {}");
    expect(p.get("entData")).toBe("Update");
    expect(p.get("revNote")).toBe("psbot 2026-06-18");
    expect(p.get("cinfo-desc")).toBe("My Event");
    expect(p.get("cinfo-private")).toBe("0");
    expect(p.get("cinfo-whoCanEdit")).toBe("anyone");
  });
});

describe("pushClashfinder", () => {
  test("POSTs the form body to the edit endpoint with login cookies", async () => {
    let captured: { url: string; init: any } | undefined;
    const res = await pushClashfinder(
      "myevent",
      { input0: "maintitle = X", input1: "act = {}", desc: "My Event", revNote: "r1" },
      { userLogin: "alex-cf,tok", phpsessid: "sess" },
      {
        fetchImpl: async (url: string, init: any) => {
          captured = { url, init };
          return { ok: true, status: 200, text: async () => "ok", url };
        },
      },
    );
    expect(captured!.url).toBe("https://clashfinder.com/s/myevent/?edit");
    expect(captured!.init.method).toBe("POST");
    expect(String(captured!.init.headers["Content-Type"])).toContain("x-www-form-urlencoded");
    expect(String(captured!.init.headers["Cookie"])).toContain("userLogin=alex-cf,tok");
    expect(String(captured!.init.headers["Cookie"])).toContain("PHPSESSID=sess");
    expect(new URLSearchParams(captured!.init.body).get("entData")).toBe("Update");
    expect(res.ok).toBe(true);
  });

  test("flags a login redirect as a stale session", async () => {
    const res = await pushClashfinder(
      "myevent",
      { input0: "maintitle = X", input1: "act = {}", desc: "d", revNote: "r" },
      { userLogin: "alex-cf,tok" },
      {
        fetchImpl: async (url: string) => ({
          ok: true,
          status: 200,
          text: async () => "<form>Please log in to continue</form>",
          url: "https://clashfinder.com/login",
        }),
      },
    );
    expect(res.ok).toBe(false);
    expect(res.staleSession).toBe(true);
  });
});
